### ISSUE TITLE
What paper are you implementing?

### ISSUE THREAD

**Issue by RahulBhalley** [s1ddok/face-landmarks-s4tf#1]
It looks interesting to me that you're kinda using EfficientNet but what exact paper for face landmarks?

**Comment by s1ddok** [comment]
@rahulbhalley actually I'm just experimenting here. I'm trying to combine [EfficientNet](https://arxiv.org/pdf/1905.11946.pdf) with [WingLoss](https://arxiv.org/pdf/1711.06753.pdf). I've repurposed EfficientNet from classification by cutting out last FC layer. Results are promising, I will share more info once I will get something beautiful :)

**Comment by RahulBhalley** [comment]
Cool, I'm looking forward to your experiments. 😀
